name: surveillance_car_app
description: Smart Surveillance Car Flutter App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Navigation
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  
  # State Management
  provider: ^6.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  
  # Networking
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  dio: ^5.3.2
  
  # Video and Media
  video_player: ^2.8.1
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  
  # Storage and Data
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  intl: ^0.18.1
  path_provider: ^2.1.1
  device_info_plus: ^9.1.1
  connectivity_plus: ^5.0.2
  
  # Charts and Graphs
  fl_chart: ^0.65.0
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # File handling
  file_picker: ^6.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
